on:
  push:
    branches:
      - pr_*

name: Auto create pr if need

jobs:
  create_pr_if_need:
    name: Create pull request if need
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: jumpserver/action-auto-pr-branch
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
