on:
  push:
    tags:
      - '*'
      - !v*

name: Auto build other tags except v.x

jobs:
  build-other-tags-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build it and upload
        uses: jumpserver/action-build-upload-assets@java
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          ASSETS_UPLOAD_DISABLED: true

      - name: Get Tag
        id: get_tag
        run: |
          echo ">>>>>>>>" && ls ./release
          TAG=$(basename ${GITHUB_REF})
          echo "::set-output name=TAG::$TAG"
