on: 
  release:
    types: [published]

name: Release Go Binaries
env:
  CMD_PATH: ./cmd/
  SUPER_SECRET: ${{ secrets.PERSONAL_GITHUB_ACTION_SECRET }}


jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: echo ::set-env name=APP_VERSION::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
    - name: Set BUILD_TIME env
      run: echo ::set-env name=BUILD_TIME::$(date)
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - uses: wangyoucao577/go-release-action@master
      with:
        super_secret: ${{ secrets.PERSONAL_GITHUB_ACTION_SECRET }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "${{ env.CMD_PATH }}"
        build_flags: -v
        ldflags: -X "main.appVersion=${{ env.APP_VERSION }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
