on: [push, pull_request, release]

name: JumpServer repos generic handler

jobs:
  generic_handler:
    name: Run generic handler
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          I18N_TOKEN: ${{ secrets.I18N_TOKEN }}
        run: |
          echo "$I18N_TOKEN"
      - name: Run generic handler
        uses: jumpserver/action-generic-handler@dev
        env:
          I18N_TOKEN: ${{ secrets.I18N_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
