on:
  pull_request:
    types:
      - opened
      - edited

name: Auto add PR label

jobs:
  add_pr_labels:
    name: Auto add pull request labels if need
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        if: ${{ !contains(github.event.pull_request.labels, '无需处理') }}
        uses: jumpserver/action-auto-label-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
